name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: TAG=${GITHUB_REF_NAME} make release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: helio_blender_addon-*.zip
